### ISSUE TITLE
Instructions on how to play

### ISSUE THREAD

**Issue by sarah2123** [sarah2123/Quiz#1]
**User Story:**
As a user, I want to access instructions so that I can understand the rules.

**Acceptance Criteria:**
- [ ] Include a "How to Play" Button.
- [ ] Clicking the “How to Play” button opens a modal with clear instructions.
- [ ] The modal should close when the user clicks outside or on a close button.

**Tasks**
- [ ] Create a "How to Play" button.
- [ ] Create a modal that displays instructions when “How to Play” is clicked.
- [ ] Add functionality to close the modal.
